labels:
  - name: automation
    description: All issues related to project automation
    color: 00e5a8
  - name: documentation
    description: All issues related to documentation
    color: fcba50
  - name: feature-request
    description: All issues related to feature requests by customers
    color: e2ea02
  - name: feature-suggestion
    description: All issues related suggestion of a new feature. These are nice to haves but not customer requests
    color: ed7e38
  - name: feature
    description: All issues related to new features
    color: 594ed3
  - name: management
    description: All issues related to management of the project
    color: f282af
  - name: proposal
    description: All current proposals
    color: c956dd
  - name: specs-defined
    description: All issues where the specifications are defined and ready to be implemented
    color: 622ec9
  - name: specs-required
    description: All issues where the specifications are still being defined and implementation should be halted
    color: a900d8
issues:
  - title: Provide NuGet badge
    description: Provide NuGet badge in the README
    milestoneName: Project Setup
    labels:
    - management
    - documentation
  - title: Provide CI badge
    description: Provide CI badge in the README
    milestoneName: Project Setup
    labels:
    - management
    - documentation
  - title: Provide MIT license
    description: Provide MIT license on the repository and clearly document in the README
    milestoneName: Project Setup
    labels:
    - management
    - documentation
  - title: Configure CI build
    description: Configure a CI build that will build & test the changes made in every PR
    milestoneName: Project Setup
    labels:
    - management
    - automation
  - title: Configure code owners
    description: Configure code owners that need to approve changes before merging them in. ([docs](https://help.github.com/articles/about-codeowners/))
    milestoneName: Project Setup
    labels:
    - management
    - automation
  - title: Configure issue templates
    description: "Configure issue templates for the following scenarios at least:
    - [ ] Bug reports
    - [ ] Feature requests
    - [ ] Support questions"
    milestoneName: Project Setup
    labels:
    - management
    - automation
  - title: Provide a README
    description: "Provide a README that clearly states the following:
    - [ ] What the focus of the project is
    - [ ] What features it has
    - [ ] How to install it"
    milestoneName: Project Setup
    labels:
    - management
    - documentation
milestones:
 - title: Project Setup
   description: All tasks related to creating a new Arcus project