issues:
  - title: Provide NuGet badge
    description: Provide NuGet badge in the README
    milestoneName: Project Setup
    labels:
    - documentation
  - title: Configure CI build
    description: Configure a CI build that will build & test the changes made in every PR
    milestoneName: Project Setup
    labels:
    - management
    - automation
  - title: Define branch policies
    description: |-
      Define branch policies on the `master` branch.
    
      It should:
    
      - [ ] Build every PR with our CI
      - [ ] Be approved by 1 person
    milestoneName: Project Setup
    labels:
    - management
    - automation
  - title: Provide CI badge
    description: Provide CI badge in the README
    milestoneName: Project Setup
    labels:
    - documentation
  - title: Configure code owners
    description: Configure code owners that need to approve changes before merging them in. ([docs](https://help.github.com/articles/about-codeowners/))
    milestoneName: Project Setup
    labels:
    - management
    - automation
  - title: Provide a README
    description: |-
      Provide a README that clearly states what the project does.
      
      ### Checklist
            
      - [ ] What the focus of the project is
      - [ ] What features it has
      - [ ] How to install it
    milestoneName: Project Setup
    labels:
    - documentation
  - title: Provide a release pipeline for MyGet.org
    description: |-
      Provide a release pipeline for MyGet.org.
      
      ### Checklist
      
      - [ ] Configure to run for every PR
      - [ ] Use 'Determine NuGet Package Version' task group to determin package version
      - [ ] Build the codebase
      - [ ] Run test suite
      - [ ] Push all NuGet packages to MyGet.org
    milestoneName: Project Setup
    labels:
    - management
    - automation
  - title: Provide a release pipeline for NuGet.org
    description: |-
      Provide a release pipeline for NuGet.org.
      
      ### Checklist
      
      - [ ] Build the codebase
      - [ ] Run test suite
      - [ ] Tag the codebase on success
      - [ ] Create a GitHub pre-release for a preview releases
      - [ ] Create a GitHub release for full releases
      - [ ] Push all NuGet packages to NuGet.org
    milestoneName: Project Setup
    labels:
    - management
    - automation
  - title: Configure Netlify for creating preview documentation
    description: |-
      Configure Netlify for creating previews of documentation changes.
      
      This allows us to more easily review documentation changes as a reviewer and also lowers the barrier to make documentation changes.
      
      ### Checklist
      
      - [ ] Create new Netlify site
      - [ ] Add Netlify configuration
      - [ ] Enforce checks on branches
    milestoneName: Project Setup
    labels:
    - management
    - automation
    - documentation
milestones:
 - title: Project Setup
   description: All tasks related to creating a new Arcus project
